[phases.setup]
aptPkgs = ["...", "python2", "g++", "build-essential"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn serve"

[variables]
NODE_ENV = "production"